const KEY='yamaju-board-v1';
const seed={
 employees:[
  {id:'e1',name:'渡邊 琉騎',department:'企画課',role:'',status:'在席',destination:'本社',purpose:'',returnTime:'',phone:'ok',direct:false,goHome:false,memo:''},
  {id:'e2',name:'山田 太郎',department:'営業部',role:'',status:'外出',destination:'YKK AP',purpose:'打合せ',returnTime:'15:30',phone:'later',direct:false,goHome:false,memo:''},
  {id:'e3',name:'佐藤 花子',department:'管理部',role:'',status:'会議',destination:'第2会議室',purpose:'社内会議',returnTime:'16:00',phone:'ng',direct:false,goHome:false,memo:''},
  {id:'e4',name:'田中 一郎',department:'工務',role:'',status:'現場',destination:'○○マンション',purpose:'現調',returnTime:'17:00',phone:'later',direct:true,goHome:true,memo:''}
 ],history:[],schedules:[]
};
let data=load();
let currentView='board';
const $=s=>document.querySelector(s);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function phoneText(v){return v==='ng'?'対応不可':v==='later'?'折返し':'対応可'}
function departments(){return [...new Set(data.employees.map(e=>e.department))].sort()}
function renderFilters(){const d=$('#departmentFilter'),prev=d.value;d.innerHTML='<option value="">すべての部署</option>'+departments().map(x=>`<option>${escapeHtml(x)}</option>`).join('');d.value=prev;const se=$('#scheduleEmployee');se.innerHTML=data.employees.map(e=>`<option value="${e.id}">${escapeHtml(e.name)}（${escapeHtml(e.department)}）</option>`).join('')}
function render(){renderFilters();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));const board=$('#board');if(currentView==='history')return renderHistory(board);if(currentView==='schedule')return renderSchedules(board);renderBoard(board)}
function renderBoard(board){const q=$('#searchInput').value.trim().toLowerCase(),dep=$('#departmentFilter').value,st=$('#statusFilter').value;const list=data.employees.filter(e=>(!q||`${e.name} ${e.destination} ${e.purpose}`.toLowerCase().includes(q))&&(!dep||e.department===dep)&&(!st||e.status===st));board.className='board';board.innerHTML='';const t=$('#employeeCardTemplate');list.forEach(e=>{const n=t.content.cloneNode(true);n.querySelector('.employee-name').textContent=e.name;n.querySelector('.employee-meta').textContent=[e.department,e.role].filter(Boolean).join(' / ');const p=n.querySelector('.status-pill');p.textContent=e.status;p.classList.add('status-'+e.status);n.querySelector('.destination').textContent=e.destination||'―';n.querySelector('.purpose').textContent=e.purpose||' ';n.querySelector('.return-time').textContent=e.returnTime||'―';n.querySelector('.phone-status').textContent=phoneText(e.phone);const tags=n.querySelector('.tag-row');if(e.direct)tags.innerHTML+='<span class="tag">直行</span>';if(e.goHome)tags.innerHTML+='<span class="tag">直帰</span>';if(e.memo)tags.innerHTML+=`<span class="tag">${escapeHtml(e.memo)}</span>`;n.querySelector('.change-btn').addEventListener('click',()=>openEdit(e.id));board.appendChild(n)});$('#summary').textContent=`表示 ${list.length}名 / 全${data.employees.length}名`;if(!list.length)board.innerHTML='<div class="empty card">該当する社員がいません</div>'}
function renderHistory(board){board.className='history-list';const rows=[...data.history].reverse();board.innerHTML=rows.length?rows.map(h=>`<article class="list-item card"><div class="list-row"><strong>${escapeHtml(h.name)}：${escapeHtml(h.before)} → ${escapeHtml(h.after)}</strong><span class="list-muted">${fmt(h.at)}</span></div><div>${escapeHtml(h.destination||'―')} ${h.source==='auto'?'<span class="tag">自動切換え</span>':'<span class="tag">手動</span>'}</div></article>`).join(''):'<div class="empty card">まだ履歴はありません</div>';$('#summary').textContent=`履歴 ${rows.length}件`}
function renderSchedules(board){board.className='schedule-list';const rows=[...data.schedules].sort((a,b)=>a.at.localeCompare(b.at));board.innerHTML='<button id="newScheduleInline" class="primary">＋ 予定を登録</button>'+ (rows.length?rows.map(s=>{const e=data.employees.find(x=>x.id===s.employeeId);return `<article class="list-item card"><div class="list-row"><strong>${escapeHtml(e?.name||'不明')}：${escapeHtml(s.status)}</strong><span class="list-muted">${fmt(s.at)}</span></div><div>${escapeHtml(s.destination||'―')} ${escapeHtml(s.purpose||'')}</div></article>`}).join(''):'<div class="empty card">自動切換え予定はありません</div>');setTimeout(()=>$('#newScheduleInline')?.addEventListener('click',openSchedule),0);$('#summary').textContent=`予定 ${rows.length}件`}
function openEdit(id){const e=data.employees.find(x=>x.id===id);$('#editEmployeeId').value=id;$('#editTitle').textContent=e.name;$('#editStatus').value=e.status;$('#editDestination').value=e.destination;$('#editPurpose').value=e.purpose;$('#editReturn').value=e.returnTime;$('#editPhone').value=e.phone;$('#editDirect').checked=e.direct;$('#editGoHome').checked=e.goHome;$('#editMemo').value=e.memo||'';$('#editDialog').showModal()}
$('#saveEditBtn').addEventListener('click',ev=>{ev.preventDefault();const id=$('#editEmployeeId').value,e=data.employees.find(x=>x.id===id);const before=e.status;Object.assign(e,{status:$('#editStatus').value,destination:$('#editDestination').value.trim(),purpose:$('#editPurpose').value.trim(),returnTime:$('#editReturn').value,phone:$('#editPhone').value,direct:$('#editDirect').checked,goHome:$('#editGoHome').checked,memo:$('#editMemo').value.trim()});data.history.push({at:new Date().toISOString(),employeeId:id,name:e.name,before,after:e.status,destination:e.destination,source:'manual'});save();$('#editDialog').close();render()})
function openSchedule(){const d=new Date();$('#scheduleDate').value=d.toISOString().slice(0,10);$('#scheduleStart').value='09:00';$('#scheduleDialog').showModal()}
$('#saveScheduleBtn').addEventListener('click',ev=>{ev.preventDefault();const date=$('#scheduleDate').value,time=$('#scheduleStart').value;if(!date||!time)return;data.schedules.push({id:crypto.randomUUID(),employeeId:$('#scheduleEmployee').value,at:`${date}T${time}:00`,status:$('#scheduleStatus').value,destination:$('#scheduleDestination').value.trim(),purpose:$('#schedulePurpose').value.trim(),returnTime:$('#scheduleReturn').value,done:false});save();$('#scheduleDialog').close();render()})
$('#addEmployeeBtn').addEventListener('click',()=>$('#employeeDialog').showModal());
$('#saveEmployeeBtn').addEventListener('click',ev=>{ev.preventDefault();const name=$('#newName').value.trim(),department=$('#newDepartment').value.trim();if(!name||!department)return;data.employees.push({id:crypto.randomUUID(),name,department,role:$('#newRole').value.trim(),status:'在席',destination:'本社',purpose:'',returnTime:'',phone:'ok',direct:false,goHome:false,memo:''});save();$('#employeeDialog').close();$('#employeeForm').reset();render()})
function autoSwitch(){const now=new Date();let changed=false;data.schedules.forEach(s=>{if(s.done)return;const at=new Date(s.at);if(at<=now){const e=data.employees.find(x=>x.id===s.employeeId);if(e){const before=e.status;Object.assign(e,{status:s.status,destination:s.destination,purpose:s.purpose,returnTime:s.returnTime});data.history.push({at:new Date().toISOString(),employeeId:e.id,name:e.name,before,after:e.status,destination:e.destination,source:'auto'});s.done=true;changed=true}}});if(changed){save();render()}}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v){return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
['searchInput','departmentFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;render()}));
$('#monitorBtn').addEventListener('click',()=>document.body.classList.toggle('monitor'));
setInterval(autoSwitch,15000);autoSwitch();render();
